#services:
#  postgres-db:
#    image: postgres:16
#    restart: always
#    environment:
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: bazaarly
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - ./backup:/docker-entrypoint-initdb.d
#
#  bazaarly-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres-db
#    ports:
#      - "8080:8080"
#    environment:
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#    restart: always
#
#volumes:
#  postgres_data:
