version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "8080:8080"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - springboot-network

volumes:
  pgdata:

networks:
  springboot-network:
